### ISSUE TITLE
能否加上进入/离开战斗的提示？

### ISSUE THREAD

**Issue by Solor** [Rubgrsch/RgsCT#1]
新增一个frame，加上进入/离开战斗以及成功打断/净化/偷取这几项重要的提示。

**Comment by Rubgrsch** [comment]
注释掉第29行`SetCVar("enableFloatingCombatText", 0)`，然后装上AdvancedInterfaceOptions，自己钩选项。

**Comment by Rubgrsch** [comment]
Added combat and interrupt in eed567259e4c3a23afe30253594aeeb8c77bb443.
Will add more soon.

**Comment by solor** [comment]
新版效果很好，感谢更新。
另外想问下，能否实现类似msbt的那种平滑的垂直滚动？

**Comment by Rubgrsch** [comment]
等我有空找下api，没研究过= =

**Comment by Rubgrsch** [comment]
看了下BLZ的他们是直接OnUpdate+SetPoint做出来的，所以还是偷懒不写了吧>.>
Closing this issue.
