### ISSUE TITLE
RgsCT's config will reset itself after relogin.

### ISSUE THREAD

**Issue by neosong1103** [Rubgrsch/RgsCT#7]
I set my RgsCT with only damage info showing on screen
But everytime I relogin the game, all info are showing up, damage, healing, taken damage etc. 
I have to go to interface-RgsCT and then check - uncheck all boxes again.

**Comment by Rubgrsch** [comment]
You need to safely exit the game (in safe zone or wait 20s outdoors) after any setting changes so that they are writing into your disk.

**Comment by neosong1103** [comment]
That is exactly what I did, and I even check the .lua file in my savevariables make sure that they are saved.
But once I relogin the game, even the box is unchecked, the info are still showing.

**Comment by neosong1103** [comment]
![9JVPQ}FZGO7UBW2%D61VILC](https://user-images.githubusercontent.com/40328026/129233334-f605ac80-5744-46bd-8034-ee9a482e54aa.png)
![`M7{L26XWO}_RLX _BW3BAB](https://user-images.githubusercontent.com/40328026/129233347-a74e3212-5acf-404c-b675-76bfb01cd4d9.png)
Everything unchecked, still showing up.

**Comment by Rubgrsch** [comment]
关掉其他所有插件再试一次。

**Comment by neosong1103** [comment]
请问近期会修复嘛

**Comment by Rubgrsch** [comment]
我已经很久没玩了，之前也从来没听说过有人遇到这个问题，所以能不能修复靠你了/摊手

在关闭其他所有插件的情况下，检查：SV的内容跟设置界面是否一致，以及设置界面与实际使用是否一致。

如果有不一致，勾选再取消是否正常。

**Comment by neosong1103** [comment]
泪目了
关闭其他所有插件情况下，SV内容跟设置界面一直，但设置界面与实际使用不一致
勾选再取消后正常。

**Comment by Rubgrsch** [comment]
测试最新的git版本。

**Comment by neosong1103** [comment]
问题解决啦！完美！

**Comment by neosong1103** [comment]
感谢老哥修复~
